begin;
create temporary table mindforge_seed(slug text,title text,body text,theme text,level smallint,structure text,concept text,answer text) on commit drop;
insert into mindforge_seed values
('ponte-do-bairro','A ponte das pequenas escolhas','Todas as manhãs, Lia atravessava a mesma ponte e notava uma mudança discreta no bairro. Um vaso novo, uma bicicleta encostada, uma conversa breve. Ao registrar esses detalhes, percebeu que a atenção não exige pressa: ela cresce quando escolhemos observar antes de concluir.','cidadania',1,'sequência temporal','atenção','observar antes de concluir'),
('horta-na-janela','Uma horta na janela','Ravi separou três recipientes e plantou ervas na janela. Primeiro controlou a água; depois, observou a luz. Nem todas as sementes cresceram no mesmo ritmo. O pequeno experimento mostrou que condições parecidas podem produzir resultados diferentes e que ajustes devem seguir evidências.','ciência',1,'causa e consequência','ajuste','ajustes seguem evidências'),
('mapa-do-passeio','O mapa do passeio','Antes do passeio, Joana marcou no mapa o ponto de partida, duas paradas e o destino. Durante o caminho, consultou apenas as referências principais. O mapa não substituiu a experiência; serviu como guia para manter a direção sem perder os detalhes do percurso.','estudos',1,'sequência','guia','o mapa orienta o percurso'),
('palavra-pelo-contexto','A palavra no contexto','Em uma reportagem, a palavra corrente poderia indicar água, eletricidade ou algo comum. A frase seguinte mencionava fios e energia. Essa pista resolveu a dúvida. Vocabulário contextual não depende de adivinhação: ele combina a palavra, as frases próximas e o tema do texto.','comunicação',2,'definição e exemplo','contexto','frases próximas esclarecem o sentido'),
('categorias-da-feira','Categorias na feira','Uma lista misturava frutas, materiais de limpeza e ferramentas. Ao agrupar itens por função, Caio encontrou repetições e percebeu o que faltava. Categorizar não muda os objetos; muda a forma de enxergar relações entre eles e reduz o esforço necessário para localizar informações.','estudos',2,'problema e solução','categorizar','agrupar reduz esforço de localização'),
('prefixos-em-acao','Pistas dentro das palavras','Ao encontrar a palavra reutilizar, Marina reconheceu o prefixo re e o verbo utilizar. A divisão não entregou todo o significado, mas ofereceu uma hipótese que ela confirmou na frase. Partes conhecidas de uma palavra funcionam como pistas, não como respostas infalíveis.','comunicação',2,'definição e exemplo','morfologia','partes da palavra oferecem pistas'),
('pausa-que-organiza','A pausa que organiza a frase','A mesma sequência de palavras pode ganhar clareza com uma vírgula ou um ponto. A pontuação indica relações, destaca contrastes e organiza o ritmo. Ler respeitando essas marcas ajuda a reunir palavras em unidades de sentido, sem transformar toda pausa em uma regra mecânica.','estudos',3,'explicação','pontuação','pontuação organiza relações e ritmo'),
('duas-formas-de-dizer','Duas formas de dizer','Parafrasear não é trocar cada palavra por um sinônimo. É preservar a ideia e reconstruí-la com outra estrutura. Quando Elisa explicou que uma rua alagou porque o bueiro estava obstruído, manteve a relação de causa mesmo usando palavras diferentes das do texto original.','comunicação',3,'causa e consequência','paráfrase','preservar a ideia com outra estrutura'),
('conectivos-na-trilha','Conectivos na trilha','A trilha parecia curta, porém exigia preparo. A palavra porém avisa que a segunda informação contrasta com a primeira. Conectivos como porque, portanto e embora funcionam como placas: mostram relações lógicas e ajudam o leitor a prever como uma ideia se liga à seguinte.','estudos',3,'comparação e contraste','conectivos','conectivos mostram relações lógicas'),
('memoria-do-jardim','O jardim lembrado','Depois de visitar um jardim, Pedro fechou o caderno e listou o que lembrava antes de rever as anotações. Esqueceu alguns nomes, mas recuperou a organização dos espaços. O esforço de buscar a informação revelou lacunas e tornou a revisão seguinte mais específica.','ciência',4,'sequência','recuperação ativa','buscar da memória revela lacunas'),
('revisar-no-momento','Revisar no momento certo','Rever uma ideia imediatamente pode dar sensação de facilidade. Esperar algum tempo exige mais esforço, mas também testa se a lembrança está disponível. Intervalos progressivos distribuem a prática, enquanto erros devolvem o conteúdo a um intervalo curto para nova tentativa.','estudos',4,'comparação e contraste','repetição espaçada','intervalos progressivos distribuem a prática'),
('explicar-para-aprender','Explicar para aprender','Ao explicar um conceito com palavras próprias, Sofia percebeu que sabia dar o exemplo, mas não justificar a causa. A autoexplicação transformou uma impressão vaga em uma dúvida concreta. Aprender também envolve localizar o que ainda não está claro e escolher a próxima pergunta.','estudos',4,'problema e solução','autoexplicação','explicar revela dúvidas concretas'),
('ler-com-objetivo','Um texto, três objetivos','Uma pessoa pode explorar um relatório para localizar seções, estudá-lo para compreender argumentos ou examiná-lo profundamente para avaliar evidências. O texto é o mesmo, mas a estratégia muda. Leitura eficiente não significa manter uma única velocidade; significa escolher atenção compatível com o objetivo.','negócios',5,'comparação e contraste','estratégia','a estratégia depende do objetivo'),
('sintese-da-reuniao','Síntese depois da reunião','Uma ata completa registra decisões, responsáveis e prazos. Uma síntese destaca relações essenciais sem repetir cada fala. Para escrevê-la, Breno separou fatos, interpretações e próximos passos. O resultado ficou menor, mas preservou o que alguém precisaria saber para agir depois da reunião.','negócios',5,'definição e exemplo','síntese','síntese preserva relações essenciais'),
('cidade-e-calor','Árvores, sombra e cidade','Ruas arborizadas podem oferecer sombra e reduzir o aquecimento de superfícies, mas o efeito depende de espécie, manutenção e distribuição. Plantar sem planejamento não resolve sozinho o desconforto térmico. Uma decisão consistente combina dados locais, participação dos moradores e acompanhamento ao longo do tempo.','cidadania',5,'problema e solução','planejamento','decisões combinam dados participação e acompanhamento');

insert into public.passages(slug,status,current_version,is_seed) select slug,'published',1,true from mindforge_seed on conflict(slug) do nothing;
insert into public.passage_versions(passage_id,version,title,body,language,theme,word_count,lexical_difficulty,syntactic_difficulty,difficulty_level,prior_knowledge,text_structure,estimated_minutes,key_concepts,license_type,author_name)
select p.id,1,s.title,s.body,'pt-BR',s.theme,array_length(regexp_split_to_array(trim(s.body),'\s+'),1),least(.95,.12+s.level*.15),least(.95,.1+s.level*.16),s.level,'nenhum conhecimento especializado',s.structure,greatest(1,ceil(array_length(regexp_split_to_array(trim(s.body),'\s+'),1)/180.0)::smallint),jsonb_build_array(s.concept),'original','Equipe MindForge — conteúdo seed original'
from mindforge_seed s join public.passages p on p.slug=s.slug on conflict(passage_id,version) do nothing;

insert into public.questions(passage_version_id,kind,prompt,weight,correct_explanation,position)
select pv.id,case when s.level<=2 then 'main_idea' when s.level<=4 then 'inference' else 'application' end,'Qual afirmação representa melhor a ideia central?',1.5,'A alternativa correta preserva a relação central do texto.',1 from mindforge_seed s join public.passages p on p.slug=s.slug join public.passage_versions pv on pv.passage_id=p.id and pv.version=1 where not exists(select 1 from public.questions q where q.passage_version_id=pv.id);
insert into public.question_options(question_id,label,is_correct,feedback,position)
select q.id,s.answer,true,'Você preservou a relação central.',1 from mindforge_seed s join public.passages p on p.slug=s.slug join public.passage_versions pv on pv.passage_id=p.id join public.questions q on q.passage_version_id=pv.id
union all select q.id,'O texto defende aumentar a velocidade em qualquer situação.',false,'O texto não faz promessa universal de velocidade.',2 from mindforge_seed s join public.passages p on p.slug=s.slug join public.passage_versions pv on pv.passage_id=p.id join public.questions q on q.passage_version_id=pv.id;
insert into public.concept_rubrics(passage_version_id,concept_id,label,required_keywords,accepted_synonyms,weight,required)
select pv.id,s.slug||'-central',s.concept,array[s.concept],array[s.answer],1,true from mindforge_seed s join public.passages p on p.slug=s.slug join public.passage_versions pv on pv.passage_id=p.id on conflict do nothing;
commit;
