"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { ArrowRight, CheckCircle2, Pause, Play, ScanLine } from "lucide-react";

type Question = { id: string; kind: string; prompt: string; options: Array<{ id: string; label: string }> };
type Passage = { id: string; title: string; body: string; wordCount: number; estimatedMinutes: number; difficultyLevel: number };
type Result = { wpm: number; comprehension: number; immediateRetention: number; delayedRetention: number; focus: number; vocabulary: number; calibration: number; effectiveIndex: number; confidence: string; profiles: string[]; priorities: string[]; identified: string[]; missing: string[]; speedFeedbackAllowed: boolean };
const steps = ["Preparação", "Leitura", "Compreensão", "Recordação", "Intervalo ativo", "Retenção", "Resultado"];

export function AssessmentFlow({ passage, questions }: { passage: Passage; questions: Question[] }) {
  const [step, setStep] = useState(0), [paused, setPaused] = useState(false), [readingSeconds, setReadingSeconds] = useState(0), [pauseSeconds, setPauseSeconds] = useState(0), [ruler, setRuler] = useState(true);
  const [answers, setAnswers] = useState<Record<string, { optionId: string; confidence: number }>>({});
  const [immediateRecall, setImmediateRecall] = useState(""), [delayedRecall, setDelayedRecall] = useState(""), [focusSelfReport, setFocusSelfReport] = useState(75), [visibilityChanges, setVisibilityChanges] = useState(0);
  const [result, setResult] = useState<Result | null>(null), [error, setError] = useState(""), [submitting, setSubmitting] = useState(false);
  const runId = useRef(crypto.randomUUID());
  useEffect(() => { const listener = () => { if (document.hidden && step > 0 && step < 6) setVisibilityChanges((value) => value + 1); }; document.addEventListener("visibilitychange", listener); return () => document.removeEventListener("visibilitychange", listener); }, [step]);
  useEffect(() => { if (step !== 1) return; const timer = window.setInterval(() => paused ? setPauseSeconds((value) => value + 1) : setReadingSeconds((value) => value + 1), 1000); return () => window.clearInterval(timer); }, [paused, step]);
  const progress = useMemo(() => Math.round((step / (steps.length - 1)) * 100), [step]);
  const allAnswered = questions.every((question) => answers[question.id]?.optionId);

  async function complete() {
    if (delayedRecall.trim().length < 10) return setError("Escreva ao menos uma frase sobre o que permaneceu na memória.");
    setSubmitting(true); setError("");
    const response = await fetch("/api/assessment/complete", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ runId: runId.current, passageVersionId: passage.id, activeSeconds: Math.max(10, readingSeconds), pauseSeconds, visibilityChanges, answers: Object.entries(answers).map(([questionId, answer]) => ({ questionId, ...answer })), immediateRecall, delayedRecall, focusSelfReport }) });
    const body = await response.json().catch(() => ({})) as { error?: string; result?: Result }; setSubmitting(false);
    if (!response.ok) return setError(body.error ?? "Não foi possível concluir a avaliação.");
    if (!body.result) return setError("A avaliação terminou sem um resultado válido.");
    setResult(body.result); setStep(6);
  }

  return <section className="assessment-flow" aria-label="Fluxo da avaliação">
    <div className="assessment-progress" aria-label={`Etapa ${step + 1} de ${steps.length}`}><div><span>{steps[step]}</span><strong>{progress}%</strong></div><i style={{ width: `${progress}%` }} /></div>
    {step === 0 && <div className="assessment-card"><p className="eyebrow">Preparação</p><h2>Seu ponto de partida, sem pressa</h2><p>Reserve cerca de 25 minutos. O resultado compara ritmo, compreensão e memória; não é diagnóstico clínico.</p><label className="readiness-check"><input id="ready" type="checkbox" /> Estou em condições confortáveis para ler, sem dor ou mal-estar.</label><label>Familiaridade com o tema<select defaultValue="baixa"><option value="baixa">Pouca familiaridade</option><option value="media">Alguma familiaridade</option><option value="alta">Conheço bastante</option></select></label><button className="button button-accent" onClick={() => { const ready = document.querySelector<HTMLInputElement>("#ready"); if (!ready?.checked) return setError("Confirme que está confortável para continuar."); setError(""); setStep(1); }}>Iniciar leitura <ArrowRight size={18} /></button></div>}
    {step === 1 && <div className="assessment-card reading-stage"><div className="reader-toolbar"><span>{passage.title} · nível {passage.difficultyLevel}</span><div><button className="icon-control" onClick={() => setRuler((value) => !value)} aria-pressed={ruler}><ScanLine size={18} /> Régua</button><button className="icon-control" onClick={() => setPaused((value) => !value)}>{paused ? <Play size={18} /> : <Pause size={18} />}{paused ? "Retomar" : "Pausar"}</button></div></div>{paused ? <div className="pause-panel"><Pause size={32} /><h2>Pausa registrada</h2><p>O tempo de pausa não entra no ritmo de leitura.</p><button className="button" onClick={() => setPaused(false)}>Retomar</button></div> : <article className={`reading-paper ${ruler ? "with-ruler" : ""}`}><h2>{passage.title}</h2>{passage.body.split(/\n+/).map((paragraph) => <p key={paragraph.slice(0, 32)}>{paragraph}</p>)}</article>}<div className="reader-footer"><span>{Math.floor(readingSeconds / 60)}:{String(readingSeconds % 60).padStart(2, "0")} ativos</span><button className="button button-accent" disabled={paused} onClick={() => setStep(2)}>Terminei a leitura</button></div></div>}
    {step === 2 && <div className="assessment-card"><p className="eyebrow">Compreensão</p><h2>Responda sem voltar ao texto</h2><div className="question-list">{questions.map((question, index) => <fieldset key={question.id}><legend>{index + 1}. {question.prompt}</legend>{question.options.map((option) => <label key={option.id}><input type="radio" name={question.id} checked={answers[question.id]?.optionId === option.id} onChange={() => setAnswers((current) => ({ ...current, [question.id]: { optionId: option.id, confidence: current[question.id]?.confidence ?? 70 } }))} />{option.label}</label>)}<label className="confidence-control">Confiança: {answers[question.id]?.confidence ?? 70}%<input type="range" min="0" max="100" value={answers[question.id]?.confidence ?? 70} onChange={(event) => setAnswers((current) => ({ ...current, [question.id]: { optionId: current[question.id]?.optionId ?? "", confidence: Number(event.target.value) } }))} /></label></fieldset>)}</div><button className="button button-accent" disabled={!allAnswered} onClick={() => setStep(3)}>Continuar</button></div>}
    {step === 3 && <div className="assessment-card"><p className="eyebrow">Recordação imediata</p><h2>O que você lembra?</h2><p>Sem consultar o texto, explique a ideia central e os pontos que a sustentam. A análise identifica conceitos da rubrica; ela não afirma compreender profundamente sua escrita.</p><label>Recordação livre<textarea rows={9} value={immediateRecall} onChange={(event) => setImmediateRecall(event.target.value)} placeholder="Escreva com suas próprias palavras…" /></label><button className="button button-accent" disabled={immediateRecall.trim().length < 10} onClick={() => setStep(4)}>Salvar recordação</button></div>}
    {step === 4 && <div className="assessment-card interval-task"><p className="eyebrow">Intervalo ativo</p><h2>Mude o foco por alguns instantes</h2><p>Complete a sequência lógica antes da recordação atrasada.</p><ol><li>Olhe para um ponto distante por alguns segundos.</li><li>Conte de 30 até 0 de três em três.</li><li>Organize mentalmente três tarefas de amanhã.</li></ol><button className="button button-accent" onClick={() => setStep(5)}>Ir para retenção</button></div>}
    {step === 5 && <div className="assessment-card"><p className="eyebrow">Retenção atrasada</p><h2>Recupere novamente</h2><p>Explique o texto mais uma vez sem voltar. Depois informe como percebeu sua estabilidade na tarefa.</p><label>O que permaneceu na memória?<textarea rows={8} value={delayedRecall} onChange={(event) => setDelayedRecall(event.target.value)} /></label><label className="confidence-control">Estabilidade percebida: {focusSelfReport}%<input type="range" min="0" max="100" value={focusSelfReport} onChange={(event) => setFocusSelfReport(Number(event.target.value))} /></label><button className="button button-accent" disabled={submitting} onClick={complete}>{submitting ? "Calculando plano…" : "Concluir e gerar meu plano"}</button></div>}
    {step === 6 && result && <div className="assessment-card result-card"><CheckCircle2 size={42} /><p className="eyebrow">Análise adaptativa concluída</p><h2>Seu perfil educacional</h2><div className="result-hero"><strong>{Math.round(result.effectiveIndex)}</strong><span>índice de leitura efetiva</span></div><div className="result-metrics"><Metric label="Compreensão" value={result.comprehension} /><Metric label="Retenção imediata" value={result.immediateRetention} /><Metric label="Retenção atrasada" value={result.delayedRetention} /><Metric label="Estabilidade" value={result.focus} /><Metric label="Vocabulário" value={result.vocabulary} /><Metric label="Calibração" value={result.calibration} /></div><p><strong>Perfil:</strong> {result.profiles.join(" · ")}</p><p><strong>Prioridades do plano:</strong> {result.priorities.join(", ")}</p><p>{result.speedFeedbackAllowed ? `Ritmo observado: ${Math.round(result.wpm)} palavras por minuto, interpretado junto às demais métricas.` : "O ritmo não será destacado enquanto compreensão e retenção precisam de estabilização."}</p><p className="notice">Confiança do resultado: {result.confidence}. Esta avaliação mede apenas seu desempenho nestas tarefas.</p><div className="result-actions"><Link className="button button-accent" href="/treino">Abrir primeiro treino</Link><Link className="button button-ghost" href="/progresso">Ver progresso</Link></div></div>}
    {error && <p className="form-status error" role="alert">{error}</p>}
  </section>;
}

function Metric({ label, value }: { label: string; value: number }) { return <div><span>{label}</span><strong>{Math.round(value * 100)}%</strong><i><b style={{ width: `${Math.round(value * 100)}%` }} /></i></div>; }
