"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, Eye, Layers3, Pause, Play, RotateCcw, ScanLine, Shuffle } from "lucide-react";
import { normalizePortuguese } from "../domain/content-analysis";
import { createSupabaseBrowserClient } from "../lib/supabase/client";

type Mode = "reading_ruler" | "meaning_groups" | "active_recall";
export type PracticeText = { id:string; title:string; body:string };
const fallback:PracticeText={id:"seed-local",title:"A leitura com propósito",body:"Uma leitura produtiva começa com uma pergunta clara. Durante o texto, o leitor relaciona ideias e ajusta o ritmo à dificuldade. Ao final, tenta recuperar o essencial sem consultar. Essa tentativa mostra o que permaneceu e orienta a próxima revisão."};

export function PracticeLab({ texts=[] }: { texts?:PracticeText[] }) {
  const available=texts.length?texts:[fallback]; const [mode,setMode]=useState<Mode>("reading_ruler"); const [index,setIndex]=useState(0); const [message,setMessage]=useState(""); const current=available[index%available.length];
  function changeText(){setIndex((value)=>(value+1)%available.length);setMessage("");}
  return <div className="practice-lab"><div className="practice-topbar"><nav aria-label="Modos de exercício"><button aria-pressed={mode==="reading_ruler"} onClick={()=>setMode("reading_ruler")}><ScanLine/> Régua seletiva</button><button aria-pressed={mode==="meaning_groups"} onClick={()=>setMode("meaning_groups")}><Layers3/> Unidades de sentido</button><button aria-pressed={mode==="active_recall"} onClick={()=>setMode("active_recall")}><RotateCcw/> Recuperação ativa</button></nav><button className="button button-ghost" onClick={changeText}><Shuffle size={17}/> Trocar texto</button></div><div className="practice-text-meta"><span>Texto {index+1} de {available.length}</span><strong>{current.title}</strong></div>{mode==="reading_ruler"&&<RulerExercise key={`${current.id}-ruler`} text={current} onDone={(score,duration)=>save(mode,score,duration,current.id,setMessage)}/>} {mode==="meaning_groups"&&<GroupsExercise key={`${current.id}-groups`} variant={index} onDone={(score)=>save(mode,score,0,current.id,setMessage)}/>} {mode==="active_recall"&&<RecallExercise key={`${current.id}-recall`} text={current} onDone={(score)=>save(mode,score,0,current.id,setMessage)}/>} {message&&<p className="form-status success" role="status">{message}</p>}</div>;
}
async function save(kind:Mode,score:number,duration:number,textId:string,setMessage:(v:string)=>void){const client=createSupabaseBrowserClient();if(!client)return setMessage("Banco indisponível.");const{data:{user}}=await client.auth.getUser();if(!user)return setMessage("Sua sessão expirou. Entre novamente para salvar.");const{error}=await client.from("practice_attempts").insert({user_id:user.id,exercise_kind:kind,score,duration_seconds:duration,metadata:{engine:"rules-3.0",passage_version_id:textId}});setMessage(error?error.message:`Tentativa salva: ${Math.round(score*100)}%. Escolha outro texto para continuar.`);}

function RulerExercise({text,onDone}:{text:PracticeText;onDone:(score:number,duration:number)=>void}){const lines=useMemo(()=>text.body.match(/[^.!?]+[.!?]+|[^.!?]+$/g)?.map((line)=>line.trim())??[text.body],[text.body]);const[line,setLine]=useState(0);const[wpm,setWpm]=useState(140);const[running,setRunning]=useState(false);const[seconds,setSeconds]=useState(0);useEffect(()=>{if(!running)return;const words=lines[line]?.split(/\s+/).length??8;const delay=Math.max(900,words/wpm*60000);const timer=window.setTimeout(()=>{setSeconds((value)=>value+Math.round(delay/1000));if(line<lines.length-1)setLine((value)=>value+1);else setRunning(false);},delay);return()=>window.clearTimeout(timer);},[running,line,lines,wpm]);return <section className="practice-card"><p className="eyebrow">Orientação visual com ritmo escolhido</p><h2>Régua seletiva</h2><p>A régua avança pelas unidades do texto no ritmo que você escolheu. Comece confortável e reduza o ritmo se a compreensão cair.</p><label className="speed-control">Ritmo da régua: <strong>{wpm} ppm</strong><input type="range" min="80" max="280" step="10" value={wpm} onChange={(event)=>setWpm(Number(event.target.value))}/></label><div className="ruler-lines">{lines.map((value,index)=><p className={index===line?"active":""} key={`${index}-${value.slice(0,20)}`}>{value}</p>)}</div><div className="practice-actions"><button className="button button-ghost" onClick={()=>setRunning((value)=>!value)}>{running?<><Pause size={17}/>Pausar</>:<><Play size={17}/>{seconds?"Retomar":"Iniciar"}</>}</button><button className="button button-ghost" disabled={line===0} onClick={()=>setLine((value)=>value-1)}>Voltar</button><button className="button button-accent" disabled={line<lines.length-1} onClick={()=>onDone(1,seconds)}><Check size={18}/> Concluir</button></div></section>}

const groupSets=[["Ao terminar / a leitura Marina / fechou o livro e escreveu / três ideias.","Ao terminar a leitura / Marina fechou o livro / e escreveu três ideias.","Ao / terminar a leitura Marina / fechou o livro e escreveu."],["Mesmo com a pausa / o leitor retomou a ideia central / e verificou a evidência.","Mesmo / com a pausa o leitor / retomou a ideia / central e verificou.","Mesmo com / a pausa o leitor retomou / a ideia central e verificou."]];
function GroupsExercise({variant,onDone}:{variant:number;onDone:(score:number)=>void}){const[choice,setChoice]=useState("");const options=groupSets[variant%groupSets.length];return <section className="practice-card"><p className="eyebrow">Fluência</p><h2>Unidades de sentido</h2><p>Qual divisão preserva melhor sujeito, ação e complementos?</p><div className="choice-stack">{options.map((option,index)=><label key={option}><input type="radio" name="groups" value={String(index)} checked={choice===String(index)} onChange={(event)=>setChoice(event.target.value)}/>{option}</label>)}</div><button className="button button-accent" disabled={!choice} onClick={()=>onDone(choice==="1"||variant%groupSets.length===1&&choice==="0"?1:0)}>Verificar e salvar</button></section>}

function RecallExercise({text,onDone}:{text:PracticeText;onDone:(score:number)=>void}){const[hidden,setHidden]=useState(false);const[answer,setAnswer]=useState("");const keywords=useMemo(()=>Array.from(new Set(normalizePortuguese(text.body).split(/\s+/).filter((word)=>word.length>6))).slice(0,6),[text.body]);const score=useMemo(()=>{const normalized=normalizePortuguese(answer);return keywords.filter((term)=>normalized.includes(term)).length/Math.max(1,Math.min(4,keywords.length));},[answer,keywords]);return <section className="practice-card"><p className="eyebrow">Memória</p><h2>Recuperação ativa</h2>{hidden?<><p>Sem olhar, reconstrua a ideia central, dois apoios e uma aplicação.</p><textarea rows={7} value={answer} onChange={(event)=>setAnswer(event.target.value)}/><button className="button button-accent" disabled={answer.trim().length<20} onClick={()=>onDone(Math.min(1,score))}>Analisar conceitos e salvar</button></>:<><div className="recall-source"><Eye size={20}/><div><strong>{text.title}</strong><p>{text.body}</p></div></div><button className="button button-accent" onClick={()=>setHidden(true)}>Ocultar e recordar</button></>}</section>}
