"use client";
import { Activity, Brain, BookOpenCheck, CalendarCheck2 } from "lucide-react";
import { Area, CartesianGrid, ComposedChart, Legend, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

export type ProgressPoint = { id:string; date:string; comprehension:number; retention:number; effective:number; source:"Avaliação"|"Sessão" };
export function ProgressDashboard({ points, completedSessions }: { points:ProgressPoint[]; completedSessions:number }) {
  const ordered=[...points].reverse(); const latest=points[0];
  return <div className="progress-dashboard"><section className="progress-kpis" aria-label="Resumo da evolução"><article><BookOpenCheck/><span>Compreensão atual</span><strong>{latest?`${Math.round(latest.comprehension)}%`:"—"}</strong></article><article><Brain/><span>Retenção atual</span><strong>{latest?`${Math.round(latest.retention)}%`:"—"}</strong></article><article><Activity/><span>Índice equilibrado</span><strong>{latest?Math.round(latest.effective):"—"}</strong></article><article><CalendarCheck2/><span>Sessões concluídas</span><strong>{completedSessions}</strong></article></section><section className="progress-chart-card"><div><p className="eyebrow">Evolução equilibrada</p><h2>Compreensão, memória e desempenho</h2><p>O ritmo nunca aparece como conquista isolada: a curva principal combina qualidade e estabilidade.</p></div><div className="chart-wrap" role="img" aria-label="Gráfico de evolução de compreensão, retenção e índice equilibrado"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={ordered} margin={{top:16,right:8,left:-18,bottom:0}}><defs><linearGradient id="effectiveFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#ff6b35" stopOpacity={.28}/><stop offset="100%" stopColor="#ff6b35" stopOpacity={.02}/></linearGradient></defs><CartesianGrid strokeDasharray="4 5" vertical={false} stroke="var(--line)"/><XAxis dataKey="date" tick={{fill:"var(--muted)",fontSize:11}}/><YAxis domain={[0,100]} tick={{fill:"var(--muted)",fontSize:11}}/><Tooltip contentStyle={{background:"var(--surface)",border:"1px solid var(--line)",borderRadius:12,color:"var(--text)"}}/><Legend/><Area type="monotone" dataKey="effective" name="Índice" stroke="#ff6b35" fill="url(#effectiveFill)" strokeWidth={3}/><Line type="monotone" dataKey="comprehension" name="Compreensão" stroke="#1e7770" strokeWidth={2} dot={{r:3}}/><Line type="monotone" dataKey="retention" name="Retenção" stroke="#7b61a8" strokeWidth={2} dot={{r:3}}/></ComposedChart></ResponsiveContainer></div></section><div className="progress-table" role="region" aria-label="Histórico acessível" tabIndex={0}><table><thead><tr><th>Data</th><th>Origem</th><th>Compreensão</th><th>Retenção</th><th>Índice</th></tr></thead><tbody>{points.map((point)=><tr key={point.id}><td>{point.date}</td><td>{point.source}</td><td>{Math.round(point.comprehension)}%</td><td>{Math.round(point.retention)}%</td><td>{Math.round(point.effective)}</td></tr>)}</tbody></table></div></div>;
}
