create extension if not exists pgcrypto;

create type public.app_role as enum ('student','content_admin','system_admin');
create type public.content_status as enum ('draft','review','approved','published','archived');
create type public.run_status as enum ('in_progress','paused','completed','abandoned');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null check (char_length(display_name) between 2 and 120), age_range text check (age_range in ('13-17','18-24','25-34','35-44','45-59','60+')), current_level smallint not null default 1 check (current_level between 1 and 5), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.user_preferences (user_id uuid primary key references public.profiles(id) on delete cascade, goals text[] not null default '{}', interests text[] not null default '{}', available_minutes smallint not null default 20 check (available_minutes in (10,15,20,30)), weekly_frequency smallint not null default 5 check (weekly_frequency between 1 and 7), primary_device text, preferred_time time, font_size smallint not null default 18 check (font_size between 16 and 28), theme text not null default 'system' check (theme in ('light','dark','system')), line_height numeric(3,2) not null default 1.6 check (line_height between 1.45 and 1.9), reminders_enabled boolean not null default false, analytics_enabled boolean not null default false, updated_at timestamptz not null default now());
create table public.user_consents (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, consent_type text not null, version text not null, granted boolean not null, granted_at timestamptz not null default now(), revoked_at timestamptz, unique(user_id,consent_type,version));
create table public.roles (id smallserial primary key, name public.app_role not null unique, description text);
create table public.user_roles (user_id uuid references public.profiles(id) on delete cascade, role_id smallint references public.roles(id) on delete restrict, granted_by uuid references public.profiles(id), created_at timestamptz not null default now(), primary key(user_id,role_id));

create table public.passages (id uuid primary key default gen_random_uuid(), slug text not null unique, status public.content_status not null default 'draft', current_version integer not null default 1 check(current_version > 0), created_by uuid references public.profiles(id), is_seed boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.passage_versions (id uuid primary key default gen_random_uuid(), passage_id uuid not null references public.passages(id) on delete cascade, version integer not null check(version > 0), title text not null, body text not null, language text not null default 'pt-BR', theme text not null, word_count integer not null check(word_count > 0), lexical_difficulty numeric(3,2) not null check(lexical_difficulty between 0 and 1), syntactic_difficulty numeric(3,2) not null check(syntactic_difficulty between 0 and 1), difficulty_level smallint not null check(difficulty_level between 1 and 5), prior_knowledge text, text_structure text not null, estimated_minutes smallint not null check(estimated_minutes > 0), key_concepts jsonb not null default '[]', license_type text not null check(license_type in ('original','licensed','open','public_domain')), author_name text not null, source_url text, created_at timestamptz not null default now(), unique(passage_id,version));
create table public.passage_tags (passage_id uuid references public.passages(id) on delete cascade, tag text not null, primary key(passage_id,tag));
create table public.questions (id uuid primary key default gen_random_uuid(), passage_version_id uuid not null references public.passage_versions(id) on delete cascade, kind text not null, prompt text not null, weight numeric(4,2) not null default 1 check(weight > 0), correct_explanation text not null, position integer not null default 0, created_at timestamptz not null default now());
create table public.question_options (id uuid primary key default gen_random_uuid(), question_id uuid not null references public.questions(id) on delete cascade, label text not null, is_correct boolean not null default false, feedback text not null, position integer not null default 0);
create table public.concept_rubrics (id uuid primary key default gen_random_uuid(), passage_version_id uuid not null references public.passage_versions(id) on delete cascade, concept_id text not null, label text not null, required_keywords text[] not null default '{}', accepted_synonyms text[] not null default '{}', forbidden_contradictions text[] not null default '{}', weight numeric(4,2) not null check(weight > 0), required boolean not null default true, unique(passage_version_id,concept_id));

create table public.assessment_runs (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, passage_version_id uuid references public.passage_versions(id), status public.run_status not null default 'in_progress', current_block text not null default 'instructions', started_at timestamptz not null default now(), completed_at timestamptz, active_seconds integer not null default 0 check(active_seconds >= 0), pause_seconds integer not null default 0 check(pause_seconds >= 0), version text not null default '1.0');
create index assessment_runs_user_started_idx on public.assessment_runs(user_id,started_at desc);
create table public.assessment_events (id bigint generated always as identity primary key, assessment_run_id uuid not null references public.assessment_runs(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, event_type text not null, payload jsonb not null default '{}', occurred_at timestamptz not null default now());
create table public.assessment_responses (id uuid primary key default gen_random_uuid(), assessment_run_id uuid not null references public.assessment_runs(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, question_id uuid references public.questions(id), response jsonb not null, score numeric(4,3) check(score between 0 and 1), confidence smallint check(confidence between 0 and 100), created_at timestamptz not null default now(), unique(assessment_run_id,question_id));
create table public.assessment_metrics (id uuid primary key default gen_random_uuid(), assessment_run_id uuid not null unique references public.assessment_runs(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, wpm numeric(7,2) not null default 0, speed_score numeric(4,3) not null check(speed_score between 0 and 1), comprehension_score numeric(4,3) not null check(comprehension_score between 0 and 1), immediate_retention_score numeric(4,3) not null check(immediate_retention_score between 0 and 1), delayed_retention_score numeric(4,3) not null check(delayed_retention_score between 0 and 1), focus_stability_score numeric(4,3) not null check(focus_stability_score between 0 and 1), vocabulary_score numeric(4,3) not null check(vocabulary_score between 0 and 1), metacognitive_calibration_score numeric(4,3) not null check(metacognitive_calibration_score between 0 and 1), effective_reading_index numeric(5,2) not null check(effective_reading_index between 0 and 100), confidence text not null check(confidence in ('baixa','moderada','alta')), created_at timestamptz not null default now());
create table public.diagnostic_results (id uuid primary key default gen_random_uuid(), assessment_run_id uuid not null unique references public.assessment_runs(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, profile_tags text[] not null, strengths text[] not null default '{}', priorities text[] not null default '{}', safety_notes text[] not null default '{}', engine_version text not null, created_at timestamptz not null default now());

create table public.training_plans (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, diagnostic_result_id uuid references public.diagnostic_results(id), status text not null default 'active' check(status in ('active','completed','superseded')), priority_weights jsonb not null, weekly_goal jsonb not null, progression_criteria jsonb not null, engine_version text not null, starts_on date not null default current_date, created_at timestamptz not null default now());
create table public.training_plan_days (id uuid primary key default gen_random_uuid(), training_plan_id uuid not null references public.training_plans(id) on delete cascade, day_number integer not null check(day_number between 1 and 56), total_minutes smallint not null check(total_minutes in (10,15,20,30)), blocks jsonb not null, status text not null default 'planned' check(status in ('planned','in_progress','completed','skipped')), scheduled_for date, unique(training_plan_id,day_number));
create table public.exercise_definitions (id uuid primary key default gen_random_uuid(), slug text not null unique, kind text not null, instruction text not null, duration_seconds integer not null check(duration_seconds > 0), difficulty numeric(3,2) not null check(difficulty between 0 and 1), target_skill text not null, scoring_criteria jsonb not null, feedback jsonb not null, accessibility jsonb not null, telemetry_events text[] not null default '{}', active boolean not null default true, created_at timestamptz not null default now());
create table public.exercise_assignments (id uuid primary key default gen_random_uuid(), training_plan_day_id uuid not null references public.training_plan_days(id) on delete cascade, exercise_definition_id uuid not null references public.exercise_definitions(id), passage_version_id uuid references public.passage_versions(id), position integer not null, allocated_minutes smallint not null check(allocated_minutes >= 0), configuration jsonb not null default '{}', unique(training_plan_day_id,position));
create table public.exercise_attempts (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, assignment_id uuid not null references public.exercise_assignments(id), idempotency_key uuid not null, response jsonb not null default '{}', score numeric(4,3) check(score between 0 and 1), started_at timestamptz not null default now(), completed_at timestamptz, unique(user_id,idempotency_key));
create table public.reading_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, training_plan_day_id uuid references public.training_plan_days(id), passage_version_id uuid references public.passage_versions(id), status public.run_status not null default 'in_progress', active_seconds integer not null default 0, total_seconds integer not null default 0, word_count integer not null default 0, wpm numeric(7,2), started_at timestamptz not null default now(), completed_at timestamptz);
create table public.session_events (id bigint generated always as identity primary key, reading_session_id uuid not null references public.reading_sessions(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, event_type text not null, payload jsonb not null default '{}', occurred_at timestamptz not null default now());

create table public.review_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, source_type text not null, source_id uuid not null, prompt text not null, answer jsonb not null, ease_factor numeric(3,2) not null default 2.5 check(ease_factor between 1.3 and 3), interval_days integer not null default 1 check(interval_days between 1 and 60), repetitions integer not null default 0 check(repetitions >= 0), due_at timestamptz not null default now(), last_score numeric(4,3), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index review_items_due_idx on public.review_items(user_id,due_at);
create table public.review_attempts (id uuid primary key default gen_random_uuid(), review_item_id uuid not null references public.review_items(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, rating text not null check(rating in ('forgot','hard','effort','easy')), was_correct boolean not null, score numeric(4,3), answered_at timestamptz not null default now());
create table public.vocabulary_items (id uuid primary key default gen_random_uuid(), term text not null, normalized_term text not null, definition text not null, examples text[] not null default '{}', language text not null default 'pt-BR', unique(normalized_term,language));
create table public.user_vocabulary (user_id uuid references public.profiles(id) on delete cascade, vocabulary_item_id uuid references public.vocabulary_items(id) on delete cascade, status text not null default 'learning', first_seen_at timestamptz not null default now(), last_seen_at timestamptz, primary key(user_id,vocabulary_item_id));

create table public.achievements (id uuid primary key default gen_random_uuid(), slug text not null unique, title text not null, description text not null, criteria jsonb not null, active boolean not null default true);
create table public.user_achievements (user_id uuid references public.profiles(id) on delete cascade, achievement_id uuid references public.achievements(id), earned_at timestamptz not null default now(), primary key(user_id,achievement_id));
create table public.streaks (user_id uuid primary key references public.profiles(id) on delete cascade, current_count integer not null default 0, longest_count integer not null default 0, last_practice_on date, freezes_available integer not null default 1, updated_at timestamptz not null default now());
create table public.content_progress (user_id uuid references public.profiles(id) on delete cascade, passage_id uuid references public.passages(id) on delete cascade, status text not null default 'not_started', progress numeric(4,3) not null default 0 check(progress between 0 and 1), updated_at timestamptz not null default now(), primary key(user_id,passage_id));
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, kind text not null, title text not null, body text not null, read_at timestamptz, created_at timestamptz not null default now());
create table public.sync_operations (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, idempotency_key uuid not null, operation_type text not null, payload_hash text not null, status text not null default 'applied', applied_at timestamptz not null default now(), unique(user_id,idempotency_key));
create table public.audit_logs (id bigint generated always as identity primary key, actor_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}', created_at timestamptz not null default now());

insert into public.roles(name,description) values ('student','Aluno'),('content_admin','Administrador de conteúdo'),('system_admin','Administrador do sistema') on conflict do nothing;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,display_name,age_range) values(new.id,coalesce(nullif(new.raw_user_meta_data->>'name',''),split_part(new.email,'@',1)),new.raw_user_meta_data->>'age_range'); insert into public.user_preferences(user_id) values(new.id); insert into public.user_consents(user_id,consent_type,version,granted) values(new.id,'terms','2026-07-draft',true),(new.id,'privacy','2026-07-draft',true),(new.id,'marketing','2026-07-draft',coalesce((new.raw_user_meta_data->>'marketing_consent')::boolean,false)); insert into public.user_roles(user_id,role_id) select new.id,id from public.roles where name='student'; return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.has_role(required_role public.app_role) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_roles ur join public.roles r on r.id=ur.role_id where ur.user_id=auth.uid() and r.name=required_role) $$;

alter table public.profiles enable row level security; alter table public.user_preferences enable row level security; alter table public.user_consents enable row level security; alter table public.user_roles enable row level security;
alter table public.assessment_runs enable row level security; alter table public.assessment_events enable row level security; alter table public.assessment_responses enable row level security; alter table public.assessment_metrics enable row level security; alter table public.diagnostic_results enable row level security;
alter table public.training_plans enable row level security; alter table public.training_plan_days enable row level security; alter table public.exercise_attempts enable row level security; alter table public.reading_sessions enable row level security; alter table public.session_events enable row level security;
alter table public.review_items enable row level security; alter table public.review_attempts enable row level security; alter table public.user_vocabulary enable row level security; alter table public.user_achievements enable row level security; alter table public.streaks enable row level security; alter table public.content_progress enable row level security; alter table public.notifications enable row level security; alter table public.sync_operations enable row level security; alter table public.audit_logs enable row level security;
alter table public.passages enable row level security; alter table public.passage_versions enable row level security; alter table public.passage_tags enable row level security; alter table public.questions enable row level security; alter table public.question_options enable row level security; alter table public.concept_rubrics enable row level security; alter table public.exercise_definitions enable row level security; alter table public.exercise_assignments enable row level security; alter table public.vocabulary_items enable row level security; alter table public.achievements enable row level security; alter table public.roles enable row level security;

create policy profiles_owner on public.profiles for all using(id=auth.uid()) with check(id=auth.uid());
create policy preferences_owner on public.user_preferences for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy consents_owner on public.user_consents for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy user_roles_read_own on public.user_roles for select using(user_id=auth.uid());
create policy assessment_runs_owner on public.assessment_runs for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy assessment_events_owner on public.assessment_events for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy assessment_responses_owner on public.assessment_responses for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy assessment_metrics_owner on public.assessment_metrics for select using(user_id=auth.uid());
create policy diagnostic_owner on public.diagnostic_results for select using(user_id=auth.uid());
create policy plans_owner on public.training_plans for select using(user_id=auth.uid());
create policy plan_days_owner on public.training_plan_days for select using(exists(select 1 from public.training_plans p where p.id=training_plan_id and p.user_id=auth.uid()));
create policy exercise_attempts_owner on public.exercise_attempts for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy reading_sessions_owner on public.reading_sessions for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy session_events_owner on public.session_events for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy review_items_owner on public.review_items for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy review_attempts_owner on public.review_attempts for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy user_vocabulary_owner on public.user_vocabulary for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy user_achievements_owner on public.user_achievements for select using(user_id=auth.uid());
create policy streaks_owner on public.streaks for select using(user_id=auth.uid());
create policy content_progress_owner on public.content_progress for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy notifications_owner on public.notifications for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy sync_owner on public.sync_operations for select using(user_id=auth.uid());
create policy published_passages on public.passages for select using(status='published' or public.has_role('content_admin') or public.has_role('system_admin'));
create policy published_versions on public.passage_versions for select using(exists(select 1 from public.passages p where p.id=passage_id and (p.status='published' or public.has_role('content_admin') or public.has_role('system_admin'))));
create policy published_tags on public.passage_tags for select using(exists(select 1 from public.passages p where p.id=passage_id and p.status='published'));
create policy published_questions on public.questions for select using(exists(select 1 from public.passage_versions pv join public.passages p on p.id=pv.passage_id where pv.id=passage_version_id and p.status='published'));
create policy published_options on public.question_options for select using(exists(select 1 from public.questions q join public.passage_versions pv on pv.id=q.passage_version_id join public.passages p on p.id=pv.passage_id where q.id=question_id and p.status='published'));
create policy published_rubrics on public.concept_rubrics for select using(exists(select 1 from public.passage_versions pv join public.passages p on p.id=pv.passage_id where pv.id=passage_version_id and p.status='published'));
create policy active_exercises on public.exercise_definitions for select using(active=true);
create policy assignment_owner on public.exercise_assignments for select using(exists(select 1 from public.training_plan_days d join public.training_plans p on p.id=d.training_plan_id where d.id=training_plan_day_id and p.user_id=auth.uid()));
create policy public_vocab on public.vocabulary_items for select using(true); create policy public_achievements on public.achievements for select using(active=true); create policy roles_read on public.roles for select using(true);
create policy content_admin_passages on public.passages for all using(public.has_role('content_admin') or public.has_role('system_admin')) with check(public.has_role('content_admin') or public.has_role('system_admin'));
create policy content_admin_versions on public.passage_versions for all using(public.has_role('content_admin') or public.has_role('system_admin')) with check(public.has_role('content_admin') or public.has_role('system_admin'));
create policy system_admin_audit on public.audit_logs for select using(public.has_role('system_admin'));
